<?php

namespace FServicios\WorkoutBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * workoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class workoutRepository extends EntityRepository
{
}
